__default__:
  jobname: "default"
  mem: "16G"
  cpus: 4
  time: "48:00:00"

repeat_modeler:
  jobname: "repeat_modeler"
  mem: "32G"
  cpus: 8
  time: "96:00:00"
  
repeat_classifier:
  jobname: "repeat_classifier"
  mem: "8G"
  cpus: 1
  time: "24:00:00"
  
te_class_denovo:
  jobname: "te_class_denovo"
  mem: "8G"
  cpus: 1
  time: "24:00:00"
  
te_class_denovo:
  jobname: "te_class_denovo"
  mem: "8G"
  cpus: 1
  time: "24:00:00"
  
join_repeats:
  jobname: "join_repeats"
  mem: "8G"
  cpus: 1
  time: "24:00:00"

repeat_masker:
  jobname: "repeat_masker"
  mem: "32G"
  cpus: 8
  time: "96:00:00"

genemark:
  jobname: "genemark"
  mem: "32G"
  cpus: 8
  time: "96:00:00"
  
prothint:
  jobname: "prothint"
  mem: "32G"
  cpus: 8
  time: "96:00:00"
  
braker:
  jobname: "braker"
  mem: "32G"
  cpus: 8
  time: "96:00:00"
  
prep_trsc:
  jobname: "prep_trsc"
  mem: "4"
  cpus: 1
  time: "1:00:00"
  
bedtools_getfasta:
  jobname: "bedtools_getfasta"
  mem: "4"
  cpus: 1
  time: "1:00:00"

transdecoder:
  jobname: "transdecoder"
  mem: "32G"
  cpus: 1
  time: "96:00:00"

trinotate_db:
  jobname: "trinotate_db"
  mem: "32G"
  cpus: 1
  time: "96:00:00"
  
tmhmm:
  jobname: "tmhmm"
  mem: "32G"
  cpus: 1
  time: "96:00:00"
  
hmmscan:
  jobname: "hmmscan"
  mem: "40G"
  cpus: 10
  time: "96:00:00"
  
blastp:
  blastp: "blastp"
  mem: "40G"
  cpus: 10
  time: "96:00:00"
  
blastx:
  blastp: "blastx"
  mem: "40G"
  cpus: 10
  time: "96:00:00"

rnammer:
  blastp: "rnammer"
  mem: "32G"
  cpus: 1
  time: "96:00:00"
  
rename_fasta_headers:
  jobname: "rename_fasta_headers"
  mem: "4"
  cpus: 1
  time: "1:00:00"

signalp:
  blastp: "signalp"
  mem: "32G"
  cpus: 1
  time: "96:00:00"
  
rename_gff:
  jobname: "rename_gff"
  mem: "4"
  cpus: 1
  time: "1:00:00"

trinotate_load:
  blastp: "trinotate_load"
  mem: "32G"
  cpus: 1
  time: "96:00:00"
  
trinotate_report:
  jobname: "trinotate_report"
  mem: "4"
  cpus: 1
  time: "1:00:00" 
  