__default__:
  jobname: "default"
  mem: "16G"
  cpus: 4
  time: "48:00:00"

repeat_masker:
  jobname: "repeat_masker"
  mem: "32G"
  cpus: 8
  time: "48:00:00"
  
repeat_modeler:
  jobname: "repeat_modeler"
  mem: "32G"
  cpus: 8
  time: "48:00:00"
  
braker_prot:
  jobname: "braker_prot"
  mem: "32G"
  cpus: 8
  time: "48:00:00"
