__default__:
  jobname: "default"
  mem: "16G"
  cpus: 4
  time: "48:00:00"

repeat_modeler:
  jobname: "repeat_modeler"
  mem: "32G"
  cpus: 8
  time: "96:00:00"
  
repeat_classifier:
  jobname: "repeat_classifier"
  mem: "8G"
  cpus: 1
  time: "24:00:00"
  
te_class_denovo:
  jobname: "te_class_denovo"
  mem: "8G"
  cpus: 1
  time: "24:00:00"
  
te_class_denovo:
  jobname: "te_class_denovo"
  mem: "8G"
  cpus: 1
  time: "24:00:00"
  
join_repeats:
  jobname: "join_repeats"
  mem: "8G"
  cpus: 1
  time: "24:00:00"

repeat_masker:
  jobname: "repeat_masker"
  mem: "32G"
  cpus: 8
  time: "96:00:00"

genemark:
  jobname: "genemark"
  mem: "32G"
  cpus: 8
  time: "96:00:00"
  
prothint:
  jobname: "prothint"
  mem: "32G"
  cpus: 8
  time: "96:00:00"
  
braker:
  jobname: "braker"
  mem: "32G"
  cpus: 8
  time: "96:00:00"
